//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WindowsTweak.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WindowsTweak.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item &quot;HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\AU&quot; -Force.
        /// </summary>
        internal static string AddRegistryPathforAU {
            get {
                return ResourceManager.GetString("AddRegistryPathforAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable-ScheduledTask -TaskName &quot;ScheduledDefrag&quot; -TaskPath &quot;\Microsoft\Windows\Defrag\&quot;.
        /// </summary>
        internal static string DisableDefrag {
            get {
                return ResourceManager.GetString("DisableDefrag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set-NetAdapterAdvancedProperty -Name * -DisplayName &quot;Flow Control&quot; -DisplayValue &quot;Disabled&quot;.
        /// </summary>
        internal static string DisableFlowControlOnNics {
            get {
                return ResourceManager.GetString("DisableFlowControlOnNics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable-NetAdapterPowerManagement -Name .
        /// </summary>
        internal static string DisablePowerManagementOnNics {
            get {
                return ResourceManager.GetString("DisablePowerManagementOnNics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable-NetAdapterBinding -Name &quot;{0}&quot; -ComponentID ms_pacer.
        /// </summary>
        internal static string DisableQOSOnNics {
            get {
                return ResourceManager.GetString("DisableQOSOnNics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Services\W32Time\Parameters.
        /// </summary>
        internal static string DisableSynchronizeTimeFromInternet {
            get {
                return ResourceManager.GetString("DisableSynchronizeTimeFromInternet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disable-NetAdapterBinding -Name &quot;* -ComponentID ms_tcpip6.
        /// </summary>
        internal static string DisableTCPIP6OnNics {
            get {
                return ResourceManager.GetString("DisableTCPIP6OnNics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -disk-timeout-ac 0.
        /// </summary>
        internal static string DiskTimeoutAC {
            get {
                return ResourceManager.GetString("DiskTimeoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -disk-timeout-dc 0.
        /// </summary>
        internal static string DiskTimeoutDC {
            get {
                return ResourceManager.GetString("DiskTimeoutDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -hibernate-timeout-ac 0.
        /// </summary>
        internal static string HibernateTimeoutAC {
            get {
                return ResourceManager.GetString("HibernateTimeoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -hibernate-timeout-dc 0.
        /// </summary>
        internal static string HibernateTimeoutDC {
            get {
                return ResourceManager.GetString("HibernateTimeoutDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -setacvalueindex 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c 54533251-82be-4824-96c1-47b60b740d00 893dee8e-2bef-41e0-89c6-b55d0929964c 100.
        /// </summary>
        internal static string MinimumProcessorStateAC {
            get {
                return ResourceManager.GetString("MinimumProcessorStateAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -setdcvalueindex 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c 54533251-82be-4824-96c1-47b60b740d00 893dee8e-2bef-41e0-89c6-b55d0929964c 100.
        /// </summary>
        internal static string MinimumProcessorStateDC {
            get {
                return ResourceManager.GetString("MinimumProcessorStateDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -monitor-timeout-ac 0.
        /// </summary>
        internal static string MonitorTimeoutAC {
            get {
                return ResourceManager.GetString("MonitorTimeoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -monitor-timeout-dc 0.
        /// </summary>
        internal static string MonitorTimeoutDC {
            get {
                return ResourceManager.GetString("MonitorTimeoutDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to c:\windows\system32\powercfg.exe.
        /// </summary>
        internal static string PowerCfg {
            get {
                return ResourceManager.GetString("PowerCfg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-ItemProperty HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\AU -Name NoAutoUpdate -Value 1.
        /// </summary>
        internal static string RegistryCurrentVersionMSAUNoAU {
            get {
                return ResourceManager.GetString("RegistryCurrentVersionMSAUNoAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate -Name AU.
        /// </summary>
        internal static string RegistryCurrentVersionMSNewAU {
            get {
                return ResourceManager.GetString("RegistryCurrentVersionMSNewAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\ -Name WindowsUpdate.
        /// </summary>
        internal static string RegistryCurrentVersionMSNewWU {
            get {
                return ResourceManager.GetString("RegistryCurrentVersionMSNewWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-ItemProperty HKCU:\SOFTWARE\Policies\Microsoft\Windows\Explorer -Name DisableNotificationCenter -Value 1.
        /// </summary>
        internal static string RegistryHKCUDisableNotificationCenter {
            get {
                return ResourceManager.GetString("RegistryHKCUDisableNotificationCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion -Name PushNotifications.
        /// </summary>
        internal static string RegistryHKCUPushNotifications {
            get {
                return ResourceManager.GetString("RegistryHKCUPushNotifications", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-ItemProperty HKCU:\SOFTWARE\Microsoft\Windows\CurrentVersion\PushNotifications -Name ToastEnabled -Value 0.
        /// </summary>
        internal static string RegistryHKCUToastEnabled {
            get {
                return ResourceManager.GetString("RegistryHKCUToastEnabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-ItemProperty HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU -Name NoAutoUpdate -Value 1.
        /// </summary>
        internal static string RegistryPoliciesMSAUNoAU {
            get {
                return ResourceManager.GetString("RegistryPoliciesMSAUNoAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate -Name AU.
        /// </summary>
        internal static string RegistryPoliciesMSNewAU {
            get {
                return ResourceManager.GetString("RegistryPoliciesMSNewAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-ItemProperty HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU -Name AUOptions -Value 1.
        /// </summary>
        internal static string RegistryPoliciesMSNewAUOptions {
            get {
                return ResourceManager.GetString("RegistryPoliciesMSNewAUOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item HKLM:\SOFTWARE\Policies\Microsoft\Windows -Name WindowsUpdate.
        /// </summary>
        internal static string RegistryPoliciesMSNewWU {
            get {
                return ResourceManager.GetString("RegistryPoliciesMSNewWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\ClassicStartMenu.
        /// </summary>
        internal static string RegistrySettingClassicStartMenu {
            get {
                return ResourceManager.GetString("RegistrySettingClassicStartMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Control\Lsa.
        /// </summary>
        internal static string RegistrySettingControlLSA {
            get {
                return ResourceManager.GetString("RegistrySettingControlLSA", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\Policies\System.
        /// </summary>
        internal static string RegistrySettingCurrentVersionPoliciesSystem {
            get {
                return ResourceManager.GetString("RegistrySettingCurrentVersionPoliciesSystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows\CurrentVersion\Explorer\HideDesktopIcons\NewStartPanel.
        /// </summary>
        internal static string RegistrySettingNewStartPanel {
            get {
                return ResourceManager.GetString("RegistrySettingNewStartPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Software\Microsoft\Windows NT\CurrentVersion\AppCompatFlags\Layers.
        /// </summary>
        internal static string RegistrySettingRunAsAdministrator {
            get {
                return ResourceManager.GetString("RegistrySettingRunAsAdministrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SYSTEM\CurrentControlSet\Control\Terminal Server.
        /// </summary>
        internal static string RegistrySettingTerminalServer {
            get {
                return ResourceManager.GetString("RegistrySettingTerminalServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New-Item HKCU:\SOFTWARE\Policies\Microsoft\Windows -Name Explorer.
        /// </summary>
        internal static string RegistrySettingWindowsExplorer {
            get {
                return ResourceManager.GetString("RegistrySettingWindowsExplorer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\AU.
        /// </summary>
        internal static string RegistrySettingWindowsUpdate {
            get {
                return ResourceManager.GetString("RegistrySettingWindowsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SOFTWARE\Microsoft\Windows NT\CurrentVersion\Winlogon.
        /// </summary>
        internal static string RegistrySettingWinLogon {
            get {
                return ResourceManager.GetString("RegistrySettingWinLogon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -setacvalueindex 381b4222-f694-41f0-9685-ff5bb260df2e 238c9fa8-0aad-41ed-83f4-97be242c8f20 29f6c1db-86da-48c5-9fdb-f2b67b1f44da 0.
        /// </summary>
        internal static string SleepTimeoutAC {
            get {
                return ResourceManager.GetString("SleepTimeoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -setacvalueindex 8c5e7fda-e8bf-4a96-9a85-a6e23a8c635c 238c9fa8-0aad-41ed-83f4-97be242c8f20 29f6c1db-86da-48c5-9fdb-f2b67b1f44da 0.
        /// </summary>
        internal static string SleepTimeoutDC {
            get {
                return ResourceManager.GetString("SleepTimeoutDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -standby-timeout-ac 0.
        /// </summary>
        internal static string StandbyTimeoutAC {
            get {
                return ResourceManager.GetString("StandbyTimeoutAC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to -change -standby-timeout-dc 0.
        /// </summary>
        internal static string StandbyTimeoutDC {
            get {
                return ResourceManager.GetString("StandbyTimeoutDC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test-Path &quot;HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate\AU&quot;.
        /// </summary>
        internal static string TestPathforAUPath {
            get {
                return ResourceManager.GetString("TestPathforAUPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test-Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate\AU.
        /// </summary>
        internal static string TestPathForPolAU {
            get {
                return ResourceManager.GetString("TestPathForPolAU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test-Path HKLM:\SOFTWARE\Policies\Microsoft\Windows\WindowsUpdate.
        /// </summary>
        internal static string TestPathForPolWU {
            get {
                return ResourceManager.GetString("TestPathForPolWU", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Test-Path &quot;HKLM:\SOFTWARE\Microsoft\Windows\CurrentVersion\WindowsUpdate&quot;.
        /// </summary>
        internal static string TestPathForWUPath {
            get {
                return ResourceManager.GetString("TestPathForWUPath", resourceCulture);
            }
        }
    }
}
